### ISSUE TITLE
Offline use 

### ISSUE THREAD

**Issue by jorometala** [formatBCE/Format-BLE-Tracker#4]
Hello,
Is it possible to use this integration in semi-offline mode.

What i mean: The esp32 will have wifi coverage from time to time just to get the new Uuid-s it need to track. Not sure if it store the UUId-s it need to track local or just report every detected uuid to home assistant and compare with the list. 

Then I need to trigger a relay on the ESP itself when it detect UUID while no wifi coverage. 
Is this possible and if yes how?

Thanks in advance.

**Comment by formatBCE** [comment]
Technically, it's possible. However, there would be a lot of code changes to do to this integration in order to work like that. Also, question remains open about logic of HA integration - it can't be moved to ESP32 easily.

What can be done:
1. Triggering some ESPHome lambda instead of sending data to MQTT. Then you'd put some callback with on/off your relay.
2. Caching list of devices to report into flash memory to initialize them on boot (now list of devices is taken from MQTT server on each boot). That would eliminate requirement of stable WiFi.
What is hard to do:
1. ESP basically just sends device ID and RSSI signal strength to integration. All logic of determining, where is device, when it goes offline and back is done on HA side. It will be really hard to move that logic to the chip. Especially Kalman filtration of signal strength.
2. Because of 1., your lambda (relay) wouldn't know, when to turn off - and would be signaled to turn on every several seconds, which is bad I guess.

All in all, I believe that for such simple thing like triggering relay on signal from beacon, it would worth writing simple sketch, or use something like Tasmota with their all-in-one software. :)
