### ISSUE TITLE
Format-BLE-Tracker with Bluetooth Proxy

### ISSUE THREAD

**Issue by Kitser** [formatBCE/Format-BLE-Tracker#6]
It would be great to use 1 esp32 for the room detection from this video and bluetooth  proxy. ESP32 Platform component must be configured to use the esp-idf framework. When compiling I get an error: src/ble-node.h:11:10: fatal error: Arduino.h: No such file or directory. 
Is it possible to use the same esp for both?

**Comment by formatBCE** [comment]
Sorry, I don't think it's possible anyways. Bluetooth does use too much of compute power and antenna time even with one purpose - so even if I would've found the way to run them both, it'd be very unstable. Bluetooth proxy is not recommended to use even with voice assistant, although latter doesn't use Bluetooth at all. It's because that thing is pretty resource-heavy.

**Comment by Kitser** [comment]
Ah okay! Thanks for the explanation!
