### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by J0han3s** [formatBCE/Format-BLE-Tracker#9]
How to debug.

My beacon is not showing in Format BLE (I am using my phone HA Companion App). I can see the beacon using a BLE scanner app on a different phone, but it is not been picked by Format BLE-Tracker.

Any tips?

**Comment by formatBCE** [comment]
Did you add UUID as tracker in HA integration?
I believe so.

Then you can see what's going on like this:
1. In ESPHome check logs of your scanner node. It should give heartbeat, and for each packet it is catching there will be log kind of `sending for [UUID]`. If it's not there, then either you put incorrect UUID in HA, or your phone somehow doesn't transmit packets (unlikely, if you're using HA companion app for Android).
2. After confirming it's sending correctly, you can debug in your MQTT. I use MQTT Explorer. Check format_ble_tracker: it has "alive" topic with all configured trackers, and separate topic for each tracker, which holds messages from ESP nodes, alongside with timestamp and RSSI. If you see messages coming to the topic with your phone UUID name, and timestamp isn't 0, and RSSI is higher than your configured min RSSI in HA - then the problem is in HA integration, and I will need to check it.

Let me know if you're stuck.

**Comment by J0han3s** [comment]
Thanks

1 - i get heart-beat, but no uid

`[00:33:22][D][format_ble:064]: BLE scan heartbeat
[00:33:27][D][format_ble:064]: BLE scan heartbeat
[00:33:32][D][format_ble:064]: BLE scan heartbeat`

In MQTT, it is showing as ALIVE   UIDXXX= True

**Comment by formatBCE** [comment]
This means that UUID is incorrect most probably.
Please check it carefully.

**Comment by J0han3s** [comment]
for UUID, should i include the hypthon , "-"

P9xxxxx-xx-xxxxxx-xxxx-xxxxxxxxxxxxxxxxxxxxx


or should i ignore the hyphens ?

**Comment by formatBCE** [comment]
Just copy it from BLE Transmitter page in your companion app settings, and paste as is when creating entry. No uppercase, no changes.

**Comment by J0han3s** [comment]
hmm, thanks - will keep trying tomorrow. Thank you so much

**Comment by formatBCE** [comment]
NP, let me know how it goes. :)

**Comment by siljelb** [comment]
I have the same, or at least a very similar, issue. I can see the `BLE scan heartbeat` messages in the ESPhome log, but no "sending for [UUID]" response. I've also copied the UUID directly, and MQTT Explorer is showing ALIVE [UUID] = true.

I'm using the Everything Presence One (https://shop.everythingsmart.io/en-no/products/everything-presence-one-kit) for this, would that make any difference?

**Comment by J0han3s** [comment]
I also could not resolve this

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by formatBCE** [comment]
Guys, i need you to connect your ESP32 to serial debugger (you can do it with web.esphome.io), click "reset" and paste any logs you have related to this integration.
There should be log of this kind:
`Adding UUID {your UUID capitalized}`

Also, could you try using it with any beacon like Tile, that can be added by MAC address - to be sure that this issue happens for UUIDs exclusively. 

So far i cannot reproduce it, using latest repo code and 2 Android phones.

**Comment by formatBCE** [comment]
P.S. `alive` topic is created by HA integration, to let ESP devices know, which devices to track. If UUID is there - that means you added device in HA - but doesn't mean ESP node picked it up. That's definitely ESP side trouble, but we can keep tracking here.

**Comment by NeoFax75** [comment]
I have my Pixel 7A setup properly, and the esp32 sees the Pixel 7A, but it does not update what room I am in.
[logs_esphome-web-0cf070_logs.txt](https://github.com/user-attachments/files/16734371/logs_esphome-web-0cf070_logs.txt)

**Comment by formatBCE** [comment]
Guys, I'm abandoning this integration. I switched to Bermuda - it's always better to use well-supported solution.

**Comment by massond** [comment]
I don't know if this will solve the problem for anybody else, but I was seeing the same thing and it turned out that I needed to remove "esp32_ble_tracker:" from my esp yaml.  I had already been using this device to track ble and that was a leftover from this.  Once I removed that, esp32_ble_presense picked up and started reporting devices.

**Comment by loryanstrant** [comment]
> Guys, I'm abandoning this integration. I switched to Bermuda - it's always better to use well-supported solution.

Thanks for the work you've done on this so far, it's been a fantastic solution and I've enjoyed using it for quite some time.
I've switched over to Bermuda as you've suggested - it's quite good.

Might I suggest that you archive the repo and put a note on the README so people know and don't keep raising issues?

**Comment by formatBCE** [comment]
Yes, will do it asap. Thought of it for a month, always forgetting...
